from __future__ import annotations
import asyncio
from database.mongodb import connect_db, get_db

SCHEMES: list[dict] = [
    {
        "scheme_id": "pmjdy",
        "scheme_name": "PM Jan Dhan Yojana (PMJDY)",
        "ministry": "Ministry of Finance",
        "description": "National financial inclusion mission providing zero-balance bank accounts with overdraft and accidental insurance cover.",
        "benefits": "Zero-balance account, RuPay debit card, ₹2 lakh accidental insurance, ₹10,000 overdraft facility",
        "eligibility": "Any Indian citizen above 10 years without a bank account",
        "income_limit": None,
        "min_age": 10,
        "max_age": None,
        "gender": "all",
        "occupation": None,
        "states": None,
        "category": "insurance",
        "application_link": "https://pmjdy.gov.in/",
        "estimated_annual_benefit": 2000.0,
        "source_url": "https://pmjdy.gov.in/",
    },
    {
        "scheme_id": "pmkisan",
        "scheme_name": "PM-KISAN Samman Nidhi",
        "ministry": "Ministry of Agriculture",
        "description": "Income support scheme providing ₹6,000/year to small and marginal farmer families in three equal installments.",
        "benefits": "₹6,000 per year direct bank transfer in 3 installments of ₹2,000",
        "eligibility": "Small and marginal farmer families owning cultivable land",
        "income_limit": None,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": ["farmer"],
        "states": None,
        "category": "grant",
        "application_link": "https://pmkisan.gov.in/",
        "estimated_annual_benefit": 6000.0,
        "source_url": "https://pmkisan.gov.in/",
    },
    {
        "scheme_id": "pmsby",
        "scheme_name": "PM Suraksha Bima Yojana (PMSBY)",
        "ministry": "Ministry of Finance",
        "description": "Accidental insurance scheme offering ₹2 lakh cover for accidental death or permanent disability at just ₹20/year.",
        "benefits": "₹2 lakh for accidental death or total disability, ₹1 lakh for partial disability",
        "eligibility": "Bank account holders aged 18–70 years",
        "income_limit": None,
        "min_age": 18,
        "max_age": 70,
        "gender": "all",
        "occupation": None,
        "states": None,
        "category": "insurance",
        "application_link": "https://jansuraksha.gov.in/",
        "estimated_annual_benefit": 200000.0,
        "source_url": "https://jansuraksha.gov.in/",
    },
    {
        "scheme_id": "pmjjby",
        "scheme_name": "PM Jeevan Jyoti Bima Yojana (PMJJBY)",
        "ministry": "Ministry of Finance",
        "description": "Life insurance scheme providing ₹2 lakh cover at ₹436/year premium for bank account holders.",
        "benefits": "₹2 lakh life insurance cover for death due to any reason",
        "eligibility": "Bank account holders aged 18–50 years",
        "income_limit": None,
        "min_age": 18,
        "max_age": 50,
        "gender": "all",
        "occupation": None,
        "states": None,
        "category": "insurance",
        "application_link": "https://jansuraksha.gov.in/",
        "estimated_annual_benefit": 200000.0,
        "source_url": "https://jansuraksha.gov.in/",
    },
    {
        "scheme_id": "atal_pension",
        "scheme_name": "Atal Pension Yojana (APY)",
        "ministry": "Ministry of Finance",
        "description": "Guaranteed pension scheme for unorganised sector workers guaranteeing fixed monthly pension after age 60.",
        "benefits": "Guaranteed monthly pension of ₹1,000–₹5,000 after age 60",
        "eligibility": "Indian citizens aged 18–40 in unorganised sector with a bank account",
        "income_limit": None,
        "min_age": 18,
        "max_age": 40,
        "gender": "all",
        "occupation": ["self_employed", "farmer", "unemployed"],
        "states": None,
        "category": "pension",
        "application_link": "https://npscra.nsdl.co.in/scheme-details.php",
        "estimated_annual_benefit": 60000.0,
        "source_url": "https://npscra.nsdl.co.in/",
    },
    {
        "scheme_id": "pmmvy",
        "scheme_name": "PM Matru Vandana Yojana (PMMVY)",
        "ministry": "Ministry of Women and Child Development",
        "description": "Maternity cash incentive for pregnant and lactating mothers for the first live birth.",
        "benefits": "₹5,000 cash benefit in installments for first live birth",
        "eligibility": "Pregnant/lactating women for first live child birth aged 19+",
        "income_limit": None,
        "min_age": 19,
        "max_age": 45,
        "gender": "female",
        "occupation": None,
        "states": None,
        "category": "grant",
        "application_link": "https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana",
        "estimated_annual_benefit": 5000.0,
        "source_url": "https://wcd.nic.in/",
    },
    {
        "scheme_id": "pmay_urban",
        "scheme_name": "PM Awas Yojana – Urban (PMAY-U)",
        "ministry": "Ministry of Housing and Urban Affairs",
        "description": "Credit-linked subsidy for home loans for economically weaker and middle-income urban groups.",
        "benefits": "Up to ₹2.67 lakh interest subsidy on home loans for first-time buyers",
        "eligibility": "First-time home buyers in urban areas with monthly income below ₹1.5 lakh",
        "income_limit": 150000.0,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": None,
        "states": None,
        "category": "subsidy",
        "application_link": "https://pmaymis.gov.in/",
        "estimated_annual_benefit": 26700.0,
        "source_url": "https://pmaymis.gov.in/",
    },
    {
        "scheme_id": "mudra",
        "scheme_name": "PM Mudra Yojana (PMMY)",
        "ministry": "Ministry of Finance",
        "description": "Micro-finance loans up to ₹10 lakh for non-corporate small business owners at concessional rates.",
        "benefits": "Shishu ₹50K / Kishore ₹5L / Tarun ₹10L loans at 7–12% interest",
        "eligibility": "Non-corporate, non-farm micro and small enterprises",
        "income_limit": None,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": ["self_employed"],
        "states": None,
        "category": "loan_support",
        "application_link": "https://www.mudra.org.in/",
        "estimated_annual_benefit": 50000.0,
        "source_url": "https://www.mudra.org.in/",
    },
    {
        "scheme_id": "stand_up_india",
        "scheme_name": "Stand-Up India Scheme",
        "ministry": "Ministry of Finance",
        "description": "Provides bank loans ₹10 lakh–₹1 crore to SC/ST or women entrepreneurs for greenfield enterprises.",
        "benefits": "Loan of ₹10 lakh to ₹1 crore for greenfield enterprise setup",
        "eligibility": "SC/ST or women entrepreneurs above 18 for greenfield enterprise",
        "income_limit": None,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": ["self_employed"],
        "states": None,
        "category": "loan_support",
        "application_link": "https://www.standupmitra.in/",
        "estimated_annual_benefit": 100000.0,
        "source_url": "https://www.standupmitra.in/",
    },
    {
        "scheme_id": "nsc",
        "scheme_name": "National Savings Certificate (NSC)",
        "ministry": "Ministry of Finance",
        "description": "Safe government-backed fixed-income instrument with 7.7% interest and Section 80C tax benefit.",
        "benefits": "7.7% annual interest compounded yearly, tax deduction u/s 80C up to ₹1.5 lakh",
        "eligibility": "Any Indian resident individual aged 18+",
        "income_limit": None,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": None,
        "states": None,
        "category": "grant",
        "application_link": "https://www.indiapost.gov.in/Financial/Pages/Content/NSC.aspx",
        "estimated_annual_benefit": 15000.0,
        "source_url": "https://www.indiapost.gov.in/",
    },
    {
        "scheme_id": "scss",
        "scheme_name": "Senior Citizens' Savings Scheme (SCSS)",
        "ministry": "Ministry of Finance",
        "description": "High-interest savings scheme for senior citizens with quarterly payouts and tax benefits.",
        "benefits": "8.2% annual interest, quarterly payouts, 80C deduction up to ₹1.5 lakh",
        "eligibility": "Indian citizens aged 60+ or 55+ if retired on superannuation",
        "income_limit": None,
        "min_age": 60,
        "max_age": None,
        "gender": "all",
        "occupation": ["retired"],
        "states": None,
        "category": "pension",
        "application_link": "https://www.indiapost.gov.in/Financial/Pages/Content/SCSS.aspx",
        "estimated_annual_benefit": 82000.0,
        "source_url": "https://www.indiapost.gov.in/",
    },
    {
        "scheme_id": "ssy",
        "scheme_name": "Sukanya Samriddhi Yojana (SSY)",
        "ministry": "Ministry of Finance",
        "description": "High-interest savings scheme for girl child education and marriage; best rate among small savings schemes.",
        "benefits": "8.2% annual interest, tax-free maturity, 80C deduction up to ₹1.5 lakh",
        "eligibility": "Parents/guardians of girl child below 10 years",
        "income_limit": None,
        "min_age": None,
        "max_age": None,
        "gender": "all",
        "occupation": None,
        "states": None,
        "category": "grant",
        "application_link": "https://www.indiapost.gov.in/Financial/Pages/Content/SSY.aspx",
        "estimated_annual_benefit": 20000.0,
        "source_url": "https://www.indiapost.gov.in/",
    },
    {
        "scheme_id": "pmay_gramin",
        "scheme_name": "PM Awas Yojana – Gramin (PMAY-G)",
        "ministry": "Ministry of Rural Development",
        "description": "Housing assistance for rural households living in kuchha or dilapidated houses.",
        "benefits": "₹1.2 lakh (plain) or ₹1.3 lakh (hilly) for constructing a pucca house",
        "eligibility": "Rural households without a pucca house or living in kuchha/dilapidated houses",
        "income_limit": None,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": ["farmer", "unemployed"],
        "states": None,
        "category": "subsidy",
        "application_link": "https://pmayg.nic.in/",
        "estimated_annual_benefit": 120000.0,
        "source_url": "https://pmayg.nic.in/",
    },
    {
        "scheme_id": "pm_ujjwala",
        "scheme_name": "PM Ujjwala Yojana (PMUY)",
        "ministry": "Ministry of Petroleum & Natural Gas",
        "description": "Free LPG connection to women from BPL households promoting clean cooking fuel.",
        "benefits": "Free LPG connection + first refill, subsidised subsequent refills",
        "eligibility": "Women from BPL/SC/ST households with monthly income < ₹2,500",
        "income_limit": 30000.0,
        "min_age": 18,
        "max_age": None,
        "gender": "female",
        "occupation": None,
        "states": None,
        "category": "subsidy",
        "application_link": "https://www.pmujjwalayojana.com/",
        "estimated_annual_benefit": 6000.0,
        "source_url": "https://www.pmujjwalayojana.com/",
    },
    {
        "scheme_id": "ayushman_bharat",
        "scheme_name": "Ayushman Bharat – PM-JAY",
        "ministry": "Ministry of Health and Family Welfare",
        "description": "₹5 lakh annual health insurance for secondary and tertiary hospitalisation for vulnerable families.",
        "benefits": "₹5 lakh health cover per family per year at empanelled hospitals",
        "eligibility": "Families identified in SECC data / BPL families with monthly income < ₹4,200",
        "income_limit": 50000.0,
        "min_age": None,
        "max_age": None,
        "gender": "all",
        "occupation": None,
        "states": None,
        "category": "insurance",
        "application_link": "https://pmjay.gov.in/",
        "estimated_annual_benefit": 500000.0,
        "source_url": "https://pmjay.gov.in/",
    },
    {
        "scheme_id": "e_shram",
        "scheme_name": "e-SHRAM Portal Registration",
        "ministry": "Ministry of Labour and Employment",
        "description": "National database for unorganised workers providing social security and accidental insurance.",
        "benefits": "₹2 lakh accidental death/disability insurance, access to future social security schemes",
        "eligibility": "Unorganised sector workers aged 16–59 not covered by EPFO/ESIC",
        "income_limit": None,
        "min_age": 16,
        "max_age": 59,
        "gender": "all",
        "occupation": ["self_employed", "farmer", "unemployed"],
        "states": None,
        "category": "insurance",
        "application_link": "https://eshram.gov.in/",
        "estimated_annual_benefit": 2000.0,
        "source_url": "https://eshram.gov.in/",
    },
    {
        "scheme_id": "nps_all",
        "scheme_name": "National Pension System (NPS) – All Citizens",
        "ministry": "Ministry of Finance",
        "description": "Voluntary retirement savings with market-linked returns and tax benefits for all citizens.",
        "benefits": "Tax deduction ₹1.5L u/s 80C + additional ₹50K u/s 80CCD(1B), market-linked growth",
        "eligibility": "Indian citizens aged 18–70",
        "income_limit": None,
        "min_age": 18,
        "max_age": 70,
        "gender": "all",
        "occupation": None,
        "states": None,
        "category": "pension",
        "application_link": "https://enps.nsdl.com/eNPS/NationalPensionSystem.html",
        "estimated_annual_benefit": 50000.0,
        "source_url": "https://npscra.nsdl.co.in/",
    },
    {
        "scheme_id": "startup_india_seed",
        "scheme_name": "Startup India Seed Fund Scheme",
        "ministry": "Ministry of Commerce and Industry",
        "description": "Financial assistance to early-stage startups for proof of concept, prototype and market entry.",
        "benefits": "Up to ₹20 lakh for PoC, ₹50 lakh for market entry as grant/soft loan",
        "eligibility": "DPIIT-recognized startups incorporated within 2 years, registered in India",
        "income_limit": None,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": ["self_employed"],
        "states": None,
        "category": "grant",
        "application_link": "https://seedfund.startupindia.gov.in/",
        "estimated_annual_benefit": 500000.0,
        "source_url": "https://seedfund.startupindia.gov.in/",
    },
    {
        "scheme_id": "kcc",
        "scheme_name": "Kisan Credit Card (KCC)",
        "ministry": "Ministry of Agriculture",
        "description": "Easy short-term credit for farmers to meet agricultural and allied activity needs at subsidised rates.",
        "benefits": "Credit up to ₹3 lakh at 7% p.a. (effectively 4% after interest subvention)",
        "eligibility": "Farmers, tenant farmers, oral lessees and sharecroppers in agriculture",
        "income_limit": None,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": ["farmer"],
        "states": None,
        "category": "loan_support",
        "application_link": "https://www.nabard.org/content.aspx?id=1175",
        "estimated_annual_benefit": 25000.0,
        "source_url": "https://www.nabard.org/",
    },
    {
        "scheme_id": "mgnregs",
        "scheme_name": "MGNREGS (NREGA) – Rural Employment",
        "ministry": "Ministry of Rural Development",
        "description": "Guarantees 100 days of wage employment per year to rural households for unskilled manual work.",
        "benefits": "100 days/year guaranteed wages at ₹200–₹350/day (state-notified rate)",
        "eligibility": "Adult members of rural households willing to do unskilled manual work",
        "income_limit": None,
        "min_age": 18,
        "max_age": None,
        "gender": "all",
        "occupation": ["farmer", "unemployed"],
        "states": None,
        "category": "grant",
        "application_link": "https://nrega.nic.in/",
        "estimated_annual_benefit": 25000.0,
        "source_url": "https://nrega.nic.in/",
    },
]


async def seed() -> None:
    await connect_db()
    db = get_db()
    col = db["schemes"]
    existing = await col.count_documents({})
    if existing == 0:
        await col.insert_many(SCHEMES)
        print(f"Seeded {len(SCHEMES)} schemes.")
    else:
        print(f"Database already has {existing} schemes. Skipping seed.")


if __name__ == "__main__":
    asyncio.run(seed())
